#! /bin/bash

MACHARCH=``

export PATH=$PATH:/usr/local/epics/base-3.14.12.8/bin/linux-x86_64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/epics/base-3.14.12.8/lib/linux-x86_64
export PYTHONPATH=$PYTHONPATH:/usr/local/epics/python-modules
export PYTHONPATH=$PYTHONPATH:/usr/local/python/bliss_modules/$MACHARCH
export EPICS_CA_MAX_ARRAY_BYTES=1048576
export EPICS_CA_ADDR_LIST=$HOSTNAME
export EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO
export EPICS_CAS_BEACON_ADDR_LIST=$HOSTNAME
export HERE=/usr/local/epics/pythonIoc
export EPICS_BASE=/usr/local/epics/base-3.14.12.8
export EPICS_HOST_ARCH='linux-x86_64'
