/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MBF;

import static MBF.MainPanel.errWin;
import fr.esrf.tangoatk.core.AttributePolledList;
import fr.esrf.tangoatk.core.ConnectionException;
import fr.esrf.tangoatk.core.attribute.NumberSpectrum;
import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;
import fr.esrf.tangoatk.widget.util.chart.JLDataView;
import java.awt.Dimension;

/**
 *
 * @author pons
 */
public class FIRWaveformPanel extends javax.swing.JFrame {

  private AttributePolledList attList;
  private String devName;

  /**
   * Creates new form FIRWaveformPanel
   */
  public FIRWaveformPanel(String devName,int fir) {
    
    initComponents();
    
    this.devName = devName;
    attList = new AttributePolledList();
    attList.addErrorListener(errWin);

    try {
      
      NumberSpectrum taps = (NumberSpectrum)attList.add(devName+"/FIR_"+fir+"_TAPS");
      tapsViewer.setModel(taps);
      NumberSpectrum waveform = (NumberSpectrum)attList.add(devName+"/FIR_"+fir+"_TAPS_S");
      waveformTapsViewer.setModel(waveform);
      
    } catch (ConnectionException ex) {      
    }
    
    tapsViewer.setHeader("Current Filter Taps");
    tapsViewer.getDataView().setMarker(JLDataView.MARKER_DOT);
    tapsViewer.setPreferredSize(new Dimension(400,200));
    tapsViewer.getXAxis().setGridVisible(true);
    tapsViewer.getY1Axis().setGridVisible(true);

    waveformTapsViewer.setHeader("Waveform Filter Taps");
    waveformTapsViewer.getDataView().setMarker(JLDataView.MARKER_DOT);
    waveformTapsViewer.setPreferredSize(new Dimension(400,200));
    waveformTapsViewer.getXAxis().setGridVisible(true);
    waveformTapsViewer.getY1Axis().setGridVisible(true);
    
    attList.setRefreshInterval(1000);
    
    setTitle("FIR Setup [" + devName + "]");
    ATKGraphicsUtils.centerFrameOnScreen(this);
    
  }
  
  public void setVisible(boolean visible) {
    if(visible)
      attList.startRefresher();
    else
      attList.stopRefresher();    
    super.setVisible(visible);
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    tapsViewer = new fr.esrf.tangoatk.widget.attribute.NumberSpectrumViewer();
    waveformTapsViewer = new fr.esrf.tangoatk.widget.attribute.NumberSpectrumViewer();
    btnPanel = new javax.swing.JPanel();
    dismissButton = new javax.swing.JButton();

    getContentPane().setLayout(new java.awt.GridBagLayout());

    tapsViewer.setBackground(java.awt.SystemColor.control);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(tapsViewer, gridBagConstraints);

    waveformTapsViewer.setBackground(java.awt.SystemColor.control);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(waveformTapsViewer, gridBagConstraints);

    btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    dismissButton.setText("Dismiss");
    dismissButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dismissButtonActionPerformed(evt);
      }
    });
    btnPanel.add(dismissButton);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    getContentPane().add(btnPanel, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_dismissButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel btnPanel;
  private javax.swing.JButton dismissButton;
  private fr.esrf.tangoatk.widget.attribute.NumberSpectrumViewer tapsViewer;
  private fr.esrf.tangoatk.widget.attribute.NumberSpectrumViewer waveformTapsViewer;
  // End of variables declaration//GEN-END:variables
}
