/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MBF;

import static MBF.MainPanel.errWin;
import fr.esrf.tangoatk.core.AttributePolledList;
import fr.esrf.tangoatk.core.ConnectionException;
import fr.esrf.tangoatk.core.attribute.NumberSpectrum;
import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;
import java.awt.Dimension;

/**
 *
 * @author pons
 */
public class SEQWindowPanel extends javax.swing.JFrame {

  private AttributePolledList attList;
  private String devName;

  /**
   * Creates new form SEQWindowPanel
   */
  public SEQWindowPanel(String devName) {

    initComponents();
    
    this.devName = devName;
    attList = new AttributePolledList();
    attList.addErrorListener(errWin);
    
    try {
      NumberSpectrum window = (NumberSpectrum)attList.add(devName+"/SEQ_WINDOW_S");
      windowViewer.setModel(window);
    } catch (ConnectionException ex) {      
    }
    
    windowViewer.setHeader("Detector Window ["+devName+"]");
    windowViewer.setPreferredSize(new Dimension(500,300));
    windowViewer.getXAxis().setGridVisible(true);
    windowViewer.getY1Axis().setGridVisible(true);
        
    attList.setRefreshInterval(1000);
    
    setTitle("Detector Window [" + devName + "]");
    ATKGraphicsUtils.centerFrameOnScreen(this);

    
  }
  
  public void setVisible(boolean visible) {
    if(visible)
      attList.startRefresher();
    else
      attList.stopRefresher();    
    super.setVisible(visible);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    windowViewer = new fr.esrf.tangoatk.widget.attribute.NumberSpectrumViewer();
    jPanel1 = new javax.swing.JPanel();
    resetButton = new javax.swing.JButton();
    dismissButton = new javax.swing.JButton();

    windowViewer.setBackground(java.awt.SystemColor.control);
    getContentPane().add(windowViewer, java.awt.BorderLayout.CENTER);

    jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    resetButton.setText("Reset");
    resetButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        resetButtonActionPerformed(evt);
      }
    });
    jPanel1.add(resetButton);

    dismissButton.setText("Dismiss");
    dismissButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dismissButtonActionPerformed(evt);
      }
    });
    jPanel1.add(dismissButton);

    getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
    setVisible(false);
  }//GEN-LAST:event_dismissButtonActionPerformed

  private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
    Utils.execCommand(devName,"SEQ_RESET_WIN_S");
  }//GEN-LAST:event_resetButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton dismissButton;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton resetButton;
  private fr.esrf.tangoatk.widget.attribute.NumberSpectrumViewer windowViewer;
  // End of variables declaration//GEN-END:variables
}
