#!/bin/bash

# Script for loading FPGA onto machine.  Must be called on target system.

set -e

BIT_FILE=amc525_lmbf.bit
while getopts 'f:h' option; do
    case "$option" in
        f)  BIT_FILE="$OPTARG" ;;
        h)  cat <<'EOF'
Usage: load_fpga [-f bit-file] [addresses]
    -f bit-file
        Optionally specify location of bit file, otherwise $BIT_FILE will
        be loaded from the current directory
EOF
            exit 0 ;;
        *)  echo >&2 'Invalid option: try -h for help'
            exit 1 ;;
    esac
done
shift $((OPTIND-1))

if (($# > 0)); then
    AMC525_IPS=("$@")
else
    AMC525_IPS=(200)
fi


# First of all ensure that nobody is trying to use the hardware
USERS="$(lsof -t /dev/amc525_lmbf.* 2>/dev/null)" || true
[[ -n $USERS ]]  &&  kill -9 $USERS

for ip in "${AMC525_IPS[@]}"; do
    ip=192.168.40.$ip
    scp "$BIT_FILE" root@$ip:/tmp/amc525_lmbf.bit
    ssh -x root@$ip amc525_lbtool fpga_load /tmp/amc525_lmbf.bit
done
