#!/bin/bash

set -e

# Script for loading FPGA into machine

AMC525_IPS=(192.168.40.200 192.168.40.201)

BIT_FILE=amc525_lmbf.bit


HERE="$(cd "$(dirname "$0")"; pwd)"

# First of all ensure that nobody is trying to use the hardware
USERS="$(lsof -t /dev/amc525_lmbf.* 2>/dev/null)" || true
[[ -n $USERS ]]  &&  kill -9 $USERS

for ip in "${AMC525_IPS[@]}"; do
    scp "$BIT_FILE" root@$ip:/tmp/amc525_lmbf.bit
    ssh -x root@$ip amc525_lbtool fpga_load /tmp/amc525_lmbf.bit
done
