# Top level makefile for building VHDL project

MBF_TOP := $(CURDIR)

include Makefile.common

include VERSION


# Get our version from git.  The name of the most recent parent tag is
# optionally followed by a commit count and a git code.
GIT_VERSION = $(shell \
    git describe --abbrev=7 --dirty --always --tags 2>/dev/null)

MAKE_LOCAL = \
    $(MAKE) -C $< -f $(MBF_TOP)/$1/Makefile.local \
        MBF_TOP=$(MBF_TOP) GIT_VERSION=$(GIT_VERSION) $(MAKECMDGOALS)


default:
.PHONY: default



# ------------------------------------------------------------------------------
# FPGA build

# The following targets are passed through to the FPGA build
FPGA_TARGETS = \
    fpga fpga_project runvivado edit_bd save_bd create_bd load_fpga fpga_built
.PHONY: $(FPGA_TARGETS)

$(FPGA_TARGETS): $(FPGA_BUILD_DIR)
	$(call MAKE_LOCAL,AMC525)

$(FPGA_BUILD_DIR):
	mkdir -p $@

clean-fpga:
	rm -rf $(FPGA_BUILD_DIR)
.PHONY: clean-fpga


# ------------------------------------------------------------------------------
# Driver build

DRIVER_TARGETS = driver insmod rmmod install-dkms driver-rpm udev
.PHONY: $(DRIVER_TARGETS)

$(DRIVER_TARGETS): $(DRIVER_BUILD_DIR)
	$(call MAKE_LOCAL,driver)

$(DRIVER_BUILD_DIR):
	mkdir -p $@

clean-driver:
	rm -rf $(DRIVER_BUILD_DIR)
.PHONY: clean-driver


# ------------------------------------------------------------------------------
# EPICS build

# The EPICS build is a pain: configure/RELEASE contains core build information
# that must be present before the built begins.  Here we construct it from our
# top level CONFIG file.

epics/configure/RELEASE: CONFIG
	echo '# Automatically generated. DO NOT EDIT THIS FILE!!!' >$@
	echo EPICS_DEVICE = $(EPICS_DEVICE) >>$@
	echo EPICS_BASE = $(EPICS_BASE) >>$@

epics: epics/configure/RELEASE
	make -C $@
.PHONY: epics

clean-epics:
	touch epics/configure/RELEASE
	make -C epics clean uninstall
	rm -f epics/configure/RELEASE
.PHONY: clean-epics


# ------------------------------------------------------------------------------
# Miscellanous other targets

matlab:
	make -C $@
.PHONY: matlab

tune_fit:
	make -C $@
.PHONY: tune_fit


print_version:
	@echo VERSION_EXTRA=$(VERSION_EXTRA)
	@echo VERSION_MAJOR=$(VERSION_MAJOR)
	@echo VERSION_MINOR=$(VERSION_MINOR)
	@echo VERSION_PATCH=$(VERSION_PATCH)
.PHONY: print_version


default: epics matlab tune_fit

install: default
	make driver-rpm
.PHONY: install

clean: clean-epics
	rm -rf $(BUILD_DIR)
	make -C matlab clean
	make -C tune_fit clean
.PHONY: clean
