# Computes tan^-1(2^-n) for CORDIC angle calculations.

import sys

from numpy import *

# Number of bits in tan inverse
BITS = 20
# Number of entries in the table
ROUNDS = 16

def generate_body():
    scale = 2**BITS / 2 / pi

    atan = arctan(2.**-(arange(ROUNDS)))
    result = int_(round_(scale * atan))

    for r in result[:-1]:
        print '        %dX"%09x",' % (BITS, r)
    print '        %dX"%09x"' % (BITS, result[-1])

print '''\
--
-- DO NOT EDIT THIS FILE !!!
--
-- This file has been automatically generated.
-- To change this file edit the source file and rebuild.
'''
for line in file(sys.argv[1]):
    if '@TABLE_BODY' in line:
        generate_body()
    else:
        print line,
