/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLEANING;

import static CLEANING.MainPanel.errWin;
import fr.esrf.tangoatk.core.AttributeList;
import fr.esrf.tangoatk.core.ConnectionException;
import fr.esrf.tangoatk.core.attribute.DevStateScalar;
import fr.esrf.tangoatk.core.attribute.NumberScalar;

/**
 *
 * @author pons
 */
public class ScraperPanel extends javax.swing.JPanel {
  
  private AttributeList attList;

  /**
   * Creates new form ScrapperPanel
   */
  public ScraperPanel(String devName) {
    
    initComponents();
    
    attList = new AttributeList();
    attList.addErrorListener(errWin);
    setterPanel.setLabelVisible(false);    
    setterPanel.setUnitVisible(false);

    try {      

      NumberScalar posModel = (NumberScalar)attList.add(devName+"/Position");
      setterPanel.setAttModel(posModel);
      DevStateScalar stateModel = (DevStateScalar)attList.add(devName+"/State");      
      stateViewer.setModel(stateModel);
      
    } catch (ConnectionException ex) {      
    }
    
    attList.setRefreshInterval(1000);
    attList.startRefresher();
        
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    stateViewer = new fr.esrf.tangoatk.widget.attribute.StateViewer();
    setterPanel = new fr.esrf.tangoatk.widget.attribute.NumberScalarSetPanel();
    jSmoothLabel1 = new fr.esrf.tangoatk.widget.util.JSmoothLabel();
    jSmoothLabel2 = new fr.esrf.tangoatk.widget.util.JSmoothLabel();

    setBorder(javax.swing.BorderFactory.createEtchedBorder());
    setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
    add(stateViewer, gridBagConstraints);

    setterPanel.setFont(new java.awt.Font("Lucida Bright", 0, 16)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    add(setterPanel, gridBagConstraints);

    jSmoothLabel1.setHorizontalAlignment(0);
    jSmoothLabel1.setOpaque(false);
    jSmoothLabel1.setText("Setpoint");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
    add(jSmoothLabel1, gridBagConstraints);

    jSmoothLabel2.setHorizontalAlignment(0);
    jSmoothLabel2.setOpaque(false);
    jSmoothLabel2.setText("Read (mm)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
    add(jSmoothLabel2, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private fr.esrf.tangoatk.widget.util.JSmoothLabel jSmoothLabel1;
  private fr.esrf.tangoatk.widget.util.JSmoothLabel jSmoothLabel2;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarSetPanel setterPanel;
  private fr.esrf.tangoatk.widget.attribute.StateViewer stateViewer;
  // End of variables declaration//GEN-END:variables
}
