#!/bin/bash

cd "$(dirname "$0")"

IOC=bin/linux-x86_64/lmbf

STATE_FILE=state
DEVICE=TS-DI-LMBF-02
HW_CONFIG=nothing
DEV_ADDR=0000:04:00.0
BUNCHES=936
CHAN0=X
CHAN1=Y
PV_LOG_LENGTH=10

exec valgrind $IOC \
    -s "$STATE_FILE" -d "$DEVICE" -C "$CHAN0,$CHAN1" \
    -H "$HW_CONFIG" -l "$PV_LOG_LENGTH" \
    -p /dev/amc525_lmbf/pci-"$DEV_ADDR"/amc525_lmbf -b $BUNCHES "$@"
