#!/bin/bash

cd "$(dirname "$0")"

IOC=bin/linux-x86_64/lmbf

HW_CONFIG=hardware_delays
SYS_CONFIG=system_config
DEV_ADDR=0000:04:00.0

DEV_PREFIX=/dev/amc525_lmbf/pci-"$DEV_ADDR"/amc525_lmbf

exec valgrind $IOC \
    -H "$HW_CONFIG" -S "$SYS_CONFIG" -p "$DEV_PREFIX" "$@"
