#!/bin/sh

cd "$(dirname "$0")"/opi
PATH="scripts/:$PATH"

DEVICE="${1:-TS-DI-TMBF-02}"

AXIS0="$(caget -t "$DEVICE:AXIS0")"  &&
AXIS1="$(caget -t "$DEVICE:AXIS1")"  &&
exec edm -x -eolc \
    -m device="$DEVICE" -m chan0="$AXIS0" -m chan1="$AXIS1" \
    lmbf/lmbf.edl
