#!/bin/sh

# cd "$(dirname "$(readlink -f "$0")")"/opi
HERE="$(dirname "$(readlink -f "$0")")"

DEVICE="$1"
if [[ -z $DEVICE ]]; then
    MACROS=()
    START=mbf_launcher.edl
else
    AXIS0="$(caget -t "$DEVICE:AXIS0")"  &&
    AXIS1="$(caget -t "$DEVICE:AXIS1")"  &&
    MODE="$(caget -t "$DEVICE:MODE")"  ||
        exit 1

    case "$MODE" in
        TMBF)   START=mbf/tmbf.edl ;;
        LMBF)   START=mbf/lmbf.edl ;;
        *)      echo >&2 "Unknown MODE: $MODE"
                exit 2 ;;
    esac

    MACROS=(
        -m device="$DEVICE"
        -m mode="$MODE"
        -m axis0="$AXIS0"
        -m axis1="$AXIS1")
    if [[ "$MODE" = LMBF ]]; then
        MACROS=("${MACROS[@]}" -m axis01="$AXIS0$AXIS1")
    fi
fi

PATH="$HERE/opi/scripts/:$PATH"
export EDMDATAFILES="$HERE"/opi/
edm -x -eolc "${MACROS[@]}" "$START" &
