#!/usr/bin/env python

# This script initialises the given MBF target

import sys
import os
import re
import time


# Load the given configuration file
config_lines = open(sys.argv[1]).readlines()
rule_expr = re.compile(r'^(?!#)([^= ]+) *= *(.*)\n')
config = dict([
    m.groups()
    for m in filter(None, map(rule_expr.match, config_lines))])

# Read required configuration parameters
device_address = config['device_address']
clock_mode = config['clock_mode']
adc_idelay = int(config['adc_idelay'])
dio_termination = int(config['dio_termination'])


# Load the driver
HERE = os.path.dirname(__file__)
sys.path.append(os.path.join(HERE, '../python'))

from lmbf.driver import driver, setup_pll, setup_adc, setup_dac

# If no device address specifed then default to card zero.
if not device_address:
    device_address = 0
regs = driver.Registers(device_address)


# Hardware initialisation
setup_pll.setup_pll(regs, clock_mode)
setup_adc.setup_adc(regs, adc_idelay)
setup_dac.setup_dac(regs)

# Set the digital IO termination
regs.SYS.CONTROL.DIO_TERM = dio_termination
