#!/usr/bin/env dls-python

# Helper script for updating waveforms
#
# Called as:
#
#   set_waveform_pv pv value
# or
#   set_waveform_pv pv value bunch
#
# If a bunch is not specified the value is written to the entire waveform

from pkg_resources import require

require('cothread')

import sys

import numpy
from cothread.catools import *


pv = sys.argv[1]
value = sys.argv[2]
if sys.argv[3:]:
    bunch = int(sys.argv[3])
else:
    bunch = None


# Type conversion functions for the cainfo datatype:
convert = [
    str,                # 0 = string
    int,                # 1 = short
    float,              # 2 = float
    int,                # 3 = enum (we're not going to support enum lookup)
    int,                # 4 = char
    int,                # 5 = long
    float,              # 6 = double
]

wf = caget(pv)
value = convert[wf.datatype](value)

if bunch is None:
    wf[:] = value
else:
    wf[bunch] = value

caput(pv, wf)
