#!/usr/bin/env dls-python

# Plotting of fits

import mbf.requires
import sys
import argparse
from matplotlib import pyplot

import support
import replay
import plotting



def parse_option(name_value):
    name, value = name_value.split('=', 1)
    value_type = type(getattr(support.Config, name))
    return (name, value_type(value))


def parse_args():
    parser = argparse.ArgumentParser(description = 'Replay and plot')
    parser.add_argument('-n', '--peaks', default = 3, type = int,
        help = 'Number of peaks to match')
    parser.add_argument('-a', '--plot_all',
        default = False, action = 'store_true',
        help = 'Request plotting of all stages of fit')
    parser.add_argument('-d', '--plot_dd',
        default = False, action = 'store_true',
        help = 'Plot derivative fits')
    parser.add_argument('-o', '--config',
        default = [], action = 'append', type = parse_option,
        help = '''Add config option, of form <name>=<value>.  The possible
            option names are %s.''' % ', '.join(support.Config._keys()))
    parser.add_argument('filename',
        help = 'Name of file to replay')
    parser.add_argument('samples', nargs = '?', default = 0, type = int,
        help = '''Number of samples to replay, set to 0 to load all samples in
            replay file.''')
    parser.add_argument('subset', nargs = argparse.REMAINDER, type = int,
        help = 'Individual samples to process')

    return parser.parse_args()


args = parse_args()
print args

# Load requested number of samples from the given file and extract the replay
# subset if requred.
s_iq = replay.load_replay(args.filename, args.samples)
if args.subset:
    s_iq = [s_iq[ix] for ix in args.subset]

plot_each = bool(args.subset) or args.plot_all

# Perform fitting on all the requested samples.
config = support.Config(args.peaks, **dict(args.config))
fitter = plotting.Fitter(
    len(s_iq), config, plot_each, args.plot_all, args.plot_dd)
replay.replay_s_iq(s_iq, fitter.fit_tune)

# If not plotting each individual fit, plot the final result.
if not plot_each:
    plotting.plot_fits(fitter.fits, fitter.tunes, fitter.errors)
    pyplot.show()

# vim: set filetype=python:
