#!/bin/bash

PYIOC_VERSION=2-11
PYIOC=/segfs/tango/cppserver/machine/diagnostic/MBF/tmp/pythonIoc/pythonIoc


# This is copied from the MBF runioc command; this is only appropriate if we're
# running on the MTCA server.
BCAST="$(
    ip address show enp1s0f3 |
    sed -n '/ inet /{ s/.* brd //; s/ .*//; p}')"
if [[ -n $BCAST ]]; then
    export EPICS_CAS_AUTO_BEACON_ADDR_LIST=NO
    export EPICS_CAS_BEACON_ADDR_LIST=$BCAST
fi

export EPICS_CA_MAX_ARRAY_BYTES=1048576

HERE="$(dirname "$0")"
exec $PYIOC "$HERE"/tune_fit_ioc "$@"
