/*----- PROTECTED REGION ID(MBFCleaningStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        MBFCleaningStateMachine.cpp
//
// description : State machine file for the MBFCleaning class
//
// project :     MBFCleaning
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Copyright (C): 2018
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <MBFCleaning.h>

/*----- PROTECTED REGION END -----*/	//	MBFCleaning::MBFCleaningStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace MBFCleaning_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_FreqMin_allowed()
 *	Description : Execution allowed for FreqMin attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_FreqMin_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FreqMin attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::FreqMinStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::FreqMinStateAllowed_WRITE

	//	Not any excluded states for FreqMin attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::FreqMinStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::FreqMinStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_FreqMax_allowed()
 *	Description : Execution allowed for FreqMax attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_FreqMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FreqMax attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::FreqMaxStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::FreqMaxStateAllowed_WRITE

	//	Not any excluded states for FreqMax attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::FreqMaxStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::FreqMaxStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_SweepTime_allowed()
 *	Description : Execution allowed for SweepTime attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_SweepTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SweepTime attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::SweepTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::SweepTimeStateAllowed_WRITE

	//	Not any excluded states for SweepTime attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::SweepTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::SweepTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Gain_allowed()
 *	Description : Execution allowed for Gain attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Gain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Gain attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::GainStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::GainStateAllowed_WRITE

	//	Not any excluded states for Gain attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::GainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::GainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_ConfigFileName_allowed()
 *	Description : Execution allowed for ConfigFileName attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_ConfigFileName_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ConfigFileName attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::ConfigFileNameStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::ConfigFileNameStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Scrapers_allowed()
 *	Description : Execution allowed for Scrapers attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Scrapers_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Scrapers attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::ScrapersStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::ScrapersStateAllowed_WRITE

	//	Not any excluded states for Scrapers attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::ScrapersStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::ScrapersStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Upp5_allowed()
 *	Description : Execution allowed for Upp5 attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Upp5_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Upp5 attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::Upp5StateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Upp5StateAllowed_WRITE

	//	Not any excluded states for Upp5 attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::Upp5StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Upp5StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Low5_allowed()
 *	Description : Execution allowed for Low5 attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Low5_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Low5 attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::Low5StateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Low5StateAllowed_WRITE

	//	Not any excluded states for Low5 attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::Low5StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Low5StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Upp25_allowed()
 *	Description : Execution allowed for Upp25 attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Upp25_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Upp25 attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::Upp25StateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Upp25StateAllowed_WRITE

	//	Not any excluded states for Upp25 attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::Upp25StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Upp25StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Low25_allowed()
 *	Description : Execution allowed for Low25 attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Low25_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Low25 attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::Low25StateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Low25StateAllowed_WRITE

	//	Not any excluded states for Low25 attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::Low25StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Low25StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Upp22_allowed()
 *	Description : Execution allowed for Upp22 attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Upp22_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Upp22 attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::Upp22StateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Upp22StateAllowed_WRITE

	//	Not any excluded states for Upp22 attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::Upp22StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::Upp22StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_ExternalSweep_allowed()
 *	Description : Execution allowed for ExternalSweep attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_ExternalSweep_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ExternalSweep attribute in Write access.
	/*----- PROTECTED REGION ID(MBFCleaning::ExternalSweepStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::ExternalSweepStateAllowed_WRITE

	//	Not any excluded states for ExternalSweep attribute in read access.
	/*----- PROTECTED REGION ID(MBFCleaning::ExternalSweepStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::ExternalSweepStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_StartCleaning_allowed()
 *	Description : Execution allowed for StartCleaning attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_StartCleaning_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartCleaning command.
	/*----- PROTECTED REGION ID(MBFCleaning::StartCleaningStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::StartCleaningStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_LoadConfigurationFile_allowed()
 *	Description : Execution allowed for LoadConfigurationFile attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_LoadConfigurationFile_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for LoadConfigurationFile command.
	/*----- PROTECTED REGION ID(MBFCleaning::LoadConfigurationFileStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::LoadConfigurationFileStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_SaveConfigurationFile_allowed()
 *	Description : Execution allowed for SaveConfigurationFile attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_SaveConfigurationFile_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SaveConfigurationFile command.
	/*----- PROTECTED REGION ID(MBFCleaning::SaveConfigurationFileStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::SaveConfigurationFileStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_GetConfigurationFilePath_allowed()
 *	Description : Execution allowed for GetConfigurationFilePath attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_GetConfigurationFilePath_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetConfigurationFilePath command.
	/*----- PROTECTED REGION ID(MBFCleaning::GetConfigurationFilePathStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::GetConfigurationFilePathStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Sweep_allowed()
 *	Description : Execution allowed for Sweep attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Sweep_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Sweep command.
	/*----- PROTECTED REGION ID(MBFCleaning::SweepStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::SweepStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_EndCleaning_allowed()
 *	Description : Execution allowed for EndCleaning attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_EndCleaning_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for EndCleaning command.
	/*----- PROTECTED REGION ID(MBFCleaning::EndCleaningStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::EndCleaningStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_DoAll_allowed()
 *	Description : Execution allowed for DoAll attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_DoAll_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for DoAll command.
	/*----- PROTECTED REGION ID(MBFCleaning::DoAllStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::DoAllStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MBFCleaning::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool MBFCleaning::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(MBFCleaning::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaning::StopStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(MBFCleaning::MBFCleaningStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	MBFCleaning::MBFCleaningStateAllowed.AdditionalMethods

}	//	End of namespace
