#!/bin/sh

PART=xc7vx690tffg1761-2


# Must be called with the following environment variables set:

: ${BUILD_DIR:?Must specify build directory}
: ${VIVADO:?Must specify path to Vivado settings file}
: ${LM_LICENSE_FILE:?Must specify Xilinx license server}

# Must be called with the following arguments

BLOCK_FILE="${1:?Must specify .bd file to edit}"

BLOCK_NAME="$(basename "$BLOCK_FILE" .bd)"

# Add block name to build directory
BUILD_DIR="$BUILD_DIR/$BLOCK_NAME"

# Normalise block file before we change directory
BLOCK_FILE="$(readlink -f "$BLOCK_FILE")"  &&

mkdir -p "$BUILD_DIR"  &&
cd "$BUILD_DIR"  &&
mkdir -p bd  &&
ln -sf "$BLOCK_FILE" bd  &&

cat <<EOF >edit_block.tcl  &&
if [file exists vivado/vivado.xpr] {
    open_project vivado/vivado.xpr
} else {
    create_project -quiet vivado vivado -part $PART
}
read_bd -quiet bd/$BLOCK_NAME.bd
start_gui
open_bd_design bd/$BLOCK_NAME.bd
validate_bd_design
save_bd_design
EOF

source "$VIVADO" &&
vivado -mode batch -source edit_block.tcl
# vivado -mode tcl -source edit_block.tcl
