#!/usr/bin/env python

# Script to trigger data capture

import sys
import argparse
import time

from lmbf.driver.driver import CONTROL, DDR0_NAME

parser = argparse.ArgumentParser(description = 'Trigger data capture')
parser.add_argument('-d', dest = 'print_device',
    default = False, action = 'store_true',
    help = 'Optionally output device name on completion')
parser.add_argument('samples', type = int,
    help = 'Number of samples to capture')

args = parser.parse_args()

# Two samples per capture, and we allow for a bit of overrun
CONTROL.MEM.COUNT = (args.samples + 1) / 2 + 16
CONTROL.MEM.COMMAND._write_fields_wo(START = 1, STOP = 1)
while CONTROL.MEM.STATUS.ENABLE:
    time.sleep(0.01)

if args.print_device:
    sys.stdout.write(DDR0_NAME)
