#!/usr/bin/env python

import sys

from driver import regs

args = [int(arg, 0) for arg in sys.argv[1:]]

bank = regs.regs[args[0]]
if len(args) == 1:
    # Read block
    print bank
elif len(args) == 2:
    # Read one register
    val = bank[args[1]]
    print '%d => %08X (%d)' % (args[1], val, val)
elif len(args) == 3:
    # Write
    bank[args[1]] = args[2]
else:
    assert False
