#!/usr/bin/env python

# Helper for setting bunch configuration

import sys
from driver import DSP0, DSP1


dsp, fir_select, gain, fir_enable, nco0_enable, nco1_enable = \
    [int(arg, 0) for arg in sys.argv[1:]]
dsp = [DSP0, DSP1][dsp]

config = dsp.BUNCH.BANK._fields_wo
config.FIR_SELECT = fir_select
config.GAIN = gain
config.FIR_ENABLE = fir_enable
config.NCO0_ENABLE = nco0_enable
config.NCO1_ENABLE = nco1_enable

dsp.BUNCH.CONFIG = 0
for n in range(936):
    dsp.BUNCH.BANK = config
