#!/usr/bin/env python

# Configuration for Analog Devices AD9684 ADC.

import time

from driver import REGS, ADC

# Power on the ADC and take it out of power down
REGS[0, 2] |= 1
while REGS[0, 1] & (1 << 3) == 0:
    pass

# Start by resetting the ADC, must sleep for 5ms before doing anything more.
ADC[0] = 0x81
time.sleep(0.005)

# 100 Ohm input termination
ADC[0x016] = 0x2C

# Configure settings for DC to 250MHz input, as described in table 9, page 26.
ADC[0x018] = 0x20               # 2.0x buffer current
ADC[0x025] = 0x0C               # 2.06 V p-p
ADC[0x030] = 0x04               # (for 2.06 V input)

# Check that we have clock
assert ADC[0x11c] == 1, 'No clock detected'

# Test mode is configured by writing register 0x550.  Useful values seem to be:
#   00  normal operation
#   04  alternating checkerboard (1555/2AAA)
#   07  Alternating 0000/3FFF
#   0F  ramp output
ADC[0x550] = 0x00

# Configure dual converter parallel interleaved output mode
ADC[0x568] = 0x01               # parallel interleaved mode (two converters)


# # Set up data capture from ADC
# ./reg 0 5 1
# # Configure best idelay
# ./reg 3 0 0x112
REGS[2, 0] = 1
REGS[3, 0] = 1
REGS[0, 3] = 0x10c
