#!/usr/bin/env python

# Simple script to report interrupt events.

import os
import select


f = os.open('/dev/amc525_lmbf.0.reg', os.O_NONBLOCK)

while True:
    r, w, x = select.select([f], [], [])
    print ord(os.read(f, 1))
