#!/usr/bin/env python

import sys

from driver import regs

args = [int(arg, 0) for arg in sys.argv[1:]]
if len(args) == 2:
    # Read
    dev = args[0]
    addr = args[1]
    data = regs.spi_read(dev, addr)
    print '%d %03X => %02X (%d)' % (dev, addr, data, data)
elif len(args) == 3:
    # Write
    regs.spi_write(args[0], args[1], args[2])
else:
    assert False
