#!/usr/bin/env python

# Simple low level script for interrogating FMC 500 SPI devices


import sys
from lmbf.driver import driver

args = [int(arg, 0) for arg in sys.argv[1:]]
assert len(args) in [2, 3], 'Invalid number of arguments'

dev = args[0]
spi = driver.SPI(driver.SYSTEM, dev)

if len(args) == 2:
    # Read
    addr = args[1]
    data = spi.read(addr)
    print '%d %03X => %02X (%d)' % (dev, addr, data, data)
elif len(args) == 3:
    # Write
    spi.write(args[1], args[2])
