#!/usr/bin/env python

# Tests DAC IO

import time

from driver import REGS, DAC

# Ensure DAC is powered on
assert REGS[0, 1] & (1 << 4), 'DAC not initialised'


test_pattern = [ 0x5555, 0x5555, 0xAAAA, 0xAAAA ]
test_pattern = [ 0x0123, 0x4567, 0x89AB, 0xCDEF ]


# Set DAC output into test mode
REGS[0, 6] = (test_pattern[1] << 16) | test_pattern[0]
REGS[0, 5] = (test_pattern[3] << 16) | test_pattern[2]
REGS[0, 2] |= 1 << 8

# Write expected test pattern into DAC
DAC[0x68] = test_pattern[0] & 0xFF
DAC[0x69] = test_pattern[0] >> 8
DAC[0x6A] = test_pattern[1] & 0xFF
DAC[0x6B] = test_pattern[1] >> 8
DAC[0x6C] = test_pattern[2] & 0xFF
DAC[0x6D] = test_pattern[2] >> 8
DAC[0x6E] = test_pattern[3] & 0xFF
DAC[0x6F] = test_pattern[3] >> 8

DAC[0x05] = 0x04
# Enable sample error detection
DAC[0x67] = 0x80
# Reset flags
DAC[0x06] = 0xFF
DAC[0x07] = 0xFF

error = [ DAC[0x70], DAC[0x71], DAC[0x72], DAC[0x73], ]
print error
