#!/usr/bin/env dls-python
#!/dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/prefix/bin/python

""" A minimal front end to the Docutils Publisher, producing HTML.  """

try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description

import register_docs

description = ('Generates (X)HTML documents from standalone reStructuredText '
               'sources.  ' + default_description)

publish_cmdline(writer_name='html', description=description)
