#!/bin/bash

# Reads key from given config file.  Called thus:
#
#   read_key file key
read_key()
{
    sed -n "/^$2 *= */{s///; p; q;}" "$1"
}

IOC_NAME="$(basename $1 ".config")"
IOC_DIR="$(cd "$(dirname $1)/../../../iocs"; pwd)"

VAR_SUBST=""
VAR_SUBST="$VAR_SUBST;s:@@DEVICE_NAME_H@@:$(read_key $1 tango_MBFControl_h_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@DEVICE_NAME_V@@:$(read_key $1 tango_MBFControl_v_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@DOOR_DEVICE_NAME_H@@:$(read_key $1 tango_door_h_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@DOOR_DEVICE_NAME_V@@:$(read_key $1 tango_door_v_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@MACRO_DEVICE_NAME@@:$(read_key $1 tango_macro_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@T2E_DEVICE_NAME_G@@:$(read_key $1 tango_T2E_g_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@T2E_DEVICE_NAME_H@@:$(read_key $1 tango_T2E_h_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@T2E_DEVICE_NAME_V@@:$(read_key $1 tango_T2E_v_devicename):"
VAR_SUBST="$VAR_SUBST;s:@@CONFIG_FILE_PATH_H@@:$(read_key $1 tango_MBFControl_h_configfilepath):"
VAR_SUBST="$VAR_SUBST;s:@@CONFIG_FILE_PATH_V@@:$(read_key $1 tango_MBFControl_v_configfilepath):"
VAR_SUBST="$VAR_SUBST;s:@@INSTANCE@@:$(read_key $1 tango_MBFControl_instance):"
sed "$VAR_SUBST" MBFControl_template.res
